[project]
name = "itk1"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "ruff>=0.9.10",
]

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
